name: Bug report
description: Report a bug or regression
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction
      description: Exact commands, inputs, and data paths to reproduce.
      placeholder: |
        npm run start -- --data ./data/dev-state.json ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Node version, storage mode (`json` or `sqlite`), and shell.
    validations:
      required: true
